# Generated by Django 4.0.8 on 2022-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
